BEGIN;
DO $proof$
DECLARE users uuid[]; g uuid; p uuid; peer uuid; bot uuid; outsider uuid; r jsonb; v bigint; hv bigint; denied boolean;
 deadline timestamptz; kind text; before_chips numeric; before_count integer; next_game uuid;
BEGIN
 SELECT array_agg(id) INTO users FROM (SELECT pr.id FROM public.profiles pr JOIN auth.users a ON a.id=pr.id WHERE pr.is_active ORDER BY pr.id LIMIT 4) q;
 IF cardinality(users)<4 THEN RAISE EXCEPTION 'proof:four_real_auth_fixtures_required'; END IF;
 PERFORM set_config('request.jwt.claim.sub',users[1]::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',users[1],'role','authenticated')::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 r:=public.create_session(gen_random_uuid(),'Rollback intent authority',false,1);
 g:=(r->>'game_id')::uuid; p:=(r->>'player_id')::uuid;
 EXECUTE 'RESET ROLE';
 INSERT INTO public.players(game_id,user_id,position,chips,waiting) VALUES(g,users[2],4,0,true) RETURNING id INTO peer;
 INSERT INTO public.players(game_id,user_id,position,chips,waiting,is_bot) VALUES(g,users[3],6,0,true,true) RETURNING id INTO bot;
 SELECT sum(chips),count(*) INTO before_chips,before_count FROM public.players WHERE game_id=g;
 EXECUTE 'SET LOCAL ROLE authenticated';
 SELECT intent_version INTO v FROM public.players WHERE id=p;
 r:=public.set_session_player_intent(g,p,v,NULL,'auto_ante',true);
 IF r->>'outcome'<>'accepted' OR (r->'player'->>'auto_ante')::boolean IS DISTINCT FROM true THEN RAISE EXCEPTION 'proof:own_preference:%',r; END IF;
 r:=public.set_session_player_intent(g,p,v,NULL,'auto_ante',true);
 IF r->>'outcome'<>'stale_identity' THEN RAISE EXCEPTION 'proof:duplicate_mutated'; END IF;
 SELECT intent_version INTO v FROM public.players WHERE id=p;
 r:=public.set_session_player_intent(g,p,v,NULL,'auto_ante_runback',true);
 IF (r->'player'->>'auto_ante')::boolean OR NOT (r->'player'->>'auto_ante_runback')::boolean THEN RAISE EXCEPTION 'proof:mutual_exclusion'; END IF;
 SELECT intent_version INTO v FROM public.players WHERE id=p;
 r:=public.set_session_player_intent(g,p,v,NULL,'stand_up_next_hand',true);
 SELECT intent_version INTO v FROM public.players WHERE id=p;
 r:=public.set_session_player_intent(g,p,v,NULL,'sit_out_next_hand',true);
 IF (r->'player'->>'stand_up_next_hand')::boolean OR NOT (r->'player'->>'sit_out_next_hand')::boolean THEN RAISE EXCEPTION 'proof:exit_mutual_exclusion'; END IF;
 SELECT intent_version INTO v FROM public.players WHERE id=p;
 r:=public.set_session_player_intent(g,p,v,NULL,'rejoin',true);
 IF NOT (r->'player'->>'waiting')::boolean OR (r->'player'->>'sit_out_next_hand')::boolean THEN RAISE EXCEPTION 'proof:rejoin'; END IF;
 denied:=false; BEGIN PERFORM public.set_session_player_intent(g,peer,0,NULL,'auto_ante',true); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:other_human'; END IF;
 SELECT intent_version INTO v FROM public.players WHERE id=bot;
 r:=public.set_session_player_intent(g,bot,v,NULL,'sit_out_next_hand',true);
 IF r->>'outcome'<>'accepted' THEN RAISE EXCEPTION 'proof:host_bot'; END IF;
 denied:=false; BEGIN UPDATE public.players SET auto_ante=false,auto_ante_runback=false,waiting=false WHERE id=p; EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:raw_intent'; END IF;
 denied:=false; BEGIN UPDATE public.games SET current_host=users[2] WHERE id=g; EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:raw_host'; END IF;
 SELECT host_version INTO hv FROM public.games WHERE id=g;
 r:=public.transfer_session_host(g,peer,hv+1);
 IF r->>'outcome'<>'stale_identity' THEN RAISE EXCEPTION 'proof:stale_host'; END IF;
 denied:=false; BEGIN PERFORM public.transfer_session_host(g,bot,hv); EXCEPTION WHEN invalid_parameter_value THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:bot_host'; END IF;
 r:=public.transfer_session_host(g,peer,hv);
 IF r->>'outcome'<>'accepted' THEN RAISE EXCEPTION 'proof:host_transfer'; END IF;
 denied:=false; BEGIN PERFORM public.transfer_session_host(g,p,hv); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:former_host_replay'; END IF;
 denied:=false; BEGIN PERFORM public.set_session_player_intent(g,bot,0,NULL,'rejoin',true); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:former_host_bot'; END IF;
 EXECUTE 'RESET ROLE';
 IF (SELECT sum(chips) FROM public.players WHERE game_id=g)<>before_chips OR (SELECT count(*) FROM public.players WHERE game_id=g)<>before_count THEN RAISE EXCEPTION 'proof:intent_money_or_identity'; END IF;

 -- Each game family enters the same neutral setup boundary.
 FOREACH kind IN ARRAY ARRAY['3-5-7','holm-game','horses','ship-captain-crew','yahtzee','cribbage','gin-rummy'] LOOP
  PERFORM set_config('app.three_five_seven_authoritative_write','on',true);
  PERFORM set_config('app.cribbage_authoritative_write','on',true);
  PERFORM set_config('app.gin_rummy_authoritative_write','on',true);
  PERFORM set_config('app.yahtzee_authoritative_write','on',true);
  UPDATE public.players SET sitting_out=false,waiting=false,sit_out_next_hand=false,stand_up_next_hand=false,
   position=CASE id WHEN p THEN 1 WHEN peer THEN 4 ELSE 6 END,status='active' WHERE game_id=g;
  deadline:=clock_timestamp()+interval '5 minutes';
  UPDATE public.games SET status='game_selection',game_type=kind,current_game_uuid=NULL,current_round=NULL,total_hands=0,
   dealer_position=1,config_deadline=deadline,config_complete=false,pending_session_end=false,current_host=users[1] WHERE id=g;
  PERFORM set_config('app.three_five_seven_authoritative_write','',true);
  PERFORM set_config('app.cribbage_authoritative_write','',true);
  PERFORM set_config('app.gin_rummy_authoritative_write','',true);
  PERFORM set_config('app.yahtzee_authoritative_write','',true);
  EXECUTE 'SET LOCAL ROLE authenticated';
  r:=public.decline_session_setup(g,1,deadline-interval '1 second');
  IF r->>'outcome'<>'stale_identity' THEN RAISE EXCEPTION 'proof:stale_setup:%',kind; END IF;
  r:=public.decline_session_setup(g,1,deadline);
  IF r->>'outcome'<>'declined' OR r->>'status'<>'game_selection' THEN RAISE EXCEPTION 'proof:setup_continue:%:%',kind,r; END IF;
  r:=public.decline_session_setup(g,1,deadline);
  IF r->>'outcome'<>'already_declined' THEN RAISE EXCEPTION 'proof:setup_duplicate:%',kind; END IF;
  EXECUTE 'RESET ROLE';
  IF (SELECT count(*) FROM public.players WHERE game_id=g)<>3 OR (SELECT sum(chips) FROM public.players WHERE game_id=g)<>before_chips THEN RAISE EXCEPTION 'proof:setup_conservation'; END IF;
  IF NOT (SELECT sitting_out FROM public.players WHERE id=p) THEN RAISE EXCEPTION 'proof:decliner_still_active'; END IF;
  IF least(abs((SELECT position FROM public.players WHERE id=peer)-(SELECT position FROM public.players WHERE id=bot)),7-abs((SELECT position FROM public.players WHERE id=peer)-(SELECT position FROM public.players WHERE id=bot)))<>3 THEN RAISE EXCEPTION 'proof:seat_projection'; END IF;
  IF coalesce(current_setting('app.three_five_seven_authoritative_write',true),'')<>'' OR coalesce(current_setting('app.gin_rummy_authoritative_write',true),'')<>'' THEN RAISE EXCEPTION 'proof:authority_leak'; END IF;
 END LOOP;
 -- Late compatibility replay cannot change a newer setup, and another actor cannot obtain its receipt.
 deadline:=(SELECT expected_deadline FROM private.session_setup_declines WHERE game_id=g ORDER BY expected_deadline LIMIT 1);
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',users[2],'role','authenticated')::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 denied:=false; BEGIN PERFORM public.decline_session_setup(g,1,deadline); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'proof:receipt_actor'; END IF;
 EXECUTE 'RESET ROLE';
 PERFORM set_config('request.jwt.claim.sub',users[1]::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',users[1],'role','authenticated')::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 r:=public.three_five_seven_decline_setup(g,1,deadline);
 IF r->>'outcome'<>'already_declined' THEN RAISE EXCEPTION 'proof:late_replay'; END IF;
 EXECUTE 'RESET ROLE';
 -- Fewer than two -> waiting, explicit queued stand -> retained row, no humans -> ended.
 UPDATE public.players SET sitting_out=false,waiting=false,stand_up_next_hand=(id=bot),position=CASE id WHEN p THEN 1 WHEN peer THEN 4 ELSE 6 END WHERE game_id=g;
 deadline:=clock_timestamp()+interval '5 minutes';
 UPDATE public.games SET status='game_selection',dealer_position=1,config_deadline=deadline,config_complete=false WHERE id=g;
 EXECUTE 'SET LOCAL ROLE authenticated';
 r:=public.decline_session_setup(g,1,deadline);
 IF r->>'status'<>'waiting' THEN RAISE EXCEPTION 'proof:waiting:%',r; END IF;
 EXECUTE 'RESET ROLE';
 IF (SELECT status FROM public.players WHERE id=bot)<>'left' OR (SELECT position FROM public.players WHERE id=bot) IS NOT NULL THEN RAISE EXCEPTION 'proof:queued_departure'; END IF;
 UPDATE public.players SET sitting_out=(id<>p),waiting=false WHERE game_id=g;
 deadline:=clock_timestamp()+interval '5 minutes';
 UPDATE public.games SET status='game_selection',dealer_position=1,config_deadline=deadline,config_complete=false WHERE id=g;
 EXECUTE 'SET LOCAL ROLE authenticated';
 r:=public.decline_session_setup(g,1,deadline);
 IF r->>'status'<>'session_ended' THEN RAISE EXCEPTION 'proof:ended:%',r; END IF;
 SELECT intent_version INTO v FROM public.players WHERE id=p;
 r:=public.set_session_player_intent(g,p,v,NULL,'rejoin',true);
 IF r->>'outcome'<>'stale_identity' THEN RAISE EXCEPTION 'proof:terminal_rejoin'; END IF;
 EXECUTE 'RESET ROLE';
 IF (SELECT count(*) FROM public.players WHERE game_id=g)<>3 THEN RAISE EXCEPTION 'proof:retained_participants'; END IF;
 -- A paused setup cannot advance. Pending end wins even when enough peers remain.
 UPDATE public.players SET status='active',sitting_out=false,waiting=false,position=CASE id WHEN p THEN 1 WHEN peer THEN 4 ELSE 6 END WHERE game_id=g;
 deadline:=clock_timestamp()+interval '5 minutes';
 UPDATE public.games SET status='game_selection',dealer_position=1,config_deadline=deadline,config_complete=false,is_paused=true,pending_session_end=true WHERE id=g;
 EXECUTE 'SET LOCAL ROLE authenticated';
 r:=public.decline_session_setup(g,1,deadline);
 IF r->>'outcome'<>'stale_identity' THEN RAISE EXCEPTION 'proof:paused_setup'; END IF;
 EXECUTE 'RESET ROLE';
 UPDATE public.games SET is_paused=false WHERE id=g;
 -- Resume can regenerate the setup deadline; use the authoritative identity.
 SELECT config_deadline INTO deadline FROM public.games WHERE id=g;
 EXECUTE 'SET LOCAL ROLE authenticated';
 r:=public.decline_session_setup(g,1,deadline);
 IF r->>'status'<>'session_ended' THEN RAISE EXCEPTION 'proof:pending_end:%',r; END IF;
 EXECUTE 'RESET ROLE';
END $proof$;
ROLLBACK;
