import { format } from "date-fns";

// Grateful Dead deep cuts
const GRATEFUL_DEAD_SONGS = [
  "Wharf Rat",
  "Stella Blue",
  "Mission in the Rain",
  "Row Jimmy",
  "Weather Report Suite",
  "Estimated Prophet",
  "Terrapin Station",
  "Here Comes Sunshine",
  "Crazy Fingers",
  "Ship of Fools",
  "Althea",
  "Black Peter",
  "Loser",
  "Dupree's Diamond Blues",
  "Dire Wolf",
  "High Time",
  "Ramble On Rose",
  "He's Gone",
  "Comes a Time",
  "Standing on the Moon",
  "Days Between",
  "So Many Roads",
  "Unbroken Chain",
  "Mountains of the Moon",
  "New Speedway Boogie",
  "Till the Morning Comes",
  "Attics of My Life",
  "To Lay Me Down",
  "Candyman",
  "Bird Song",
  "Deal",
  "Brokedown Palace",
  "Jack Straw",
  "Morning Dew",
  "Playing in the Band",
  "The Wheel",
  "Let It Grow",
  "Scarlet > Fire",
  "Help > Slip > Frank",
  "China > Rider",
];

// Phish songs
const PHISH_SONGS = [
  "You Enjoy Myself",
  "Divided Sky",
  "Fluffhead",
  "Reba",
  "Stash",
  "Tweezer",
  "Harry Hood",
  "Mike's Song",
  "Weekapaug Groove",
  "Ghost",
  "Bathtub Gin",
  "Chalk Dust Torture",
  "Down with Disease",
  "Antelope",
  "Hood",
  "Limb by Limb",
  "Sand",
  "Carini",
  "Simple",
  "Free",
  "Piper",
  "Maze",
  "Waste",
  "Bouncing",
  "Moma Dance",
  "Birds of a Feather",
  "Back on the Train",
  "46 Days",
  "Undermind",
  "Scents and Subtle Sounds",
  "Mercury",
  "Everything's Right",
  "Ruby Waves",
  "Soul Planet",
  "Thread",
  "Beneath a Sea of Stars",
  "Set Your Soul Free",
  "Lonely Trip",
  "Steam",
  "Lawn Boy",
  "Possum",
  "Wilson",
  "Rift",
  "Split Open and Melt",
  "The Curtain With",
];

// Peoria streets
const PEORIA_STREETS = [
  "Grandview Drive",
  "Knoxville Avenue",
  "Adams Street",
  "University Street",
  "War Memorial Drive",
  "Pioneer Parkway",
  "Prospect Road",
  "Main Street",
  "Sterling Avenue",
  "Glen Avenue",
  "Sheridan Road",
  "Western Avenue",
  "Farmington Road",
  "Allen Road",
  "Lake Avenue",
  "Wisconsin Avenue",
  "Jefferson Avenue",
  "Monroe Street",
  "Hamilton Boulevard",
  "Nebraska Avenue",
];

// Peoria high schools
const PEORIA_HIGH_SCHOOLS = [
  "Peoria High",
  "Richwoods",
  "Manual",
  "Woodruff",
  "Limestone",
  "Dunlap",
  "Notre Dame",
  "East Peoria",
  "Metamora",
  "Illinois Valley Central",
  "Pekin",
];

// Custom Peoria additions
const PEORIA_CUSTOM = [
  "Half Loin w/ PJ Chz",
  "Pork Chop Sammy",
  "Ched Nugs",
  "Mini Tacos",
  "Cheese FF",
  "Sampler",
  "Potato Skins",
  "Egg Roll",
  "Ribeye Sammy",
  "SW Ranch",
  "Peoria Stadium",
  "Par-a-Dice",
  "War Drive",
  "Farm Rd",
  "Duck's Place",
  "Gondola Deluxe",
  "Grandview Hotel",
  "Short Change",
  "Generations",
  "Blue Magoo",
  "King Orange",
  "Agatucci's",
  "Lou's Drive In",
  "Sheridan Village",
  "Lakeview Museum",
  "Grandview Motel",
  "SOPs",
  "Sullivan's",
  "Nick's Place",
  "Grand Prarie",
  "Main St.",
  "Big Al's",
  "Columbia Terrace",
  "Casey's",
];

// Chicago athletes - NO WHITE SOX, Cubs players post-2010 only
const CHICAGO_ATHLETES = [
  // Bears
  "Walter Payton",
  "Dick Butkus",
  "Brian Urlacher",
  "Gale Sayers",
  "Mike Singletary",
  "Richard Dent",
  "Devin Hester",
  "Lance Briggs",
  "Matt Forte",
  "Peanut Tillman",
  "Julius Peppers",
  "Khalil Mack",
  "Roquan Smith",
  "Eddie Jackson",
  // Bulls
  "Michael Jordan",
  "Scottie Pippen",
  "Derrick Rose",
  "Joakim Noah",
  "Luol Deng",
  "Jimmy Butler",
  "Taj Gibson",
  "Kirk Hinrich",
  "Ben Gordon",
  "Zach LaVine",
  "DeMar DeRozan",
  "Coby White",
  // Blackhawks
  "Patrick Kane",
  "Jonathan Toews",
  "Duncan Keith",
  "Brent Seabrook",
  "Marian Hossa",
  "Patrick Sharp",
  "Corey Crawford",
  "Artemi Panarin",
  "Alex DeBrincat",
  "Connor Bedard",
  // Cubs (2008+)
  "Anthony Rizzo",
  "Kris Bryant",
  "Javier Baez",
  "Kyle Schwarber",
  "Addison Russell",
  "Willson Contreras",
  "David Ross",
  "Ben Zobrist",
  "Dexter Fowler",
  "Jake Arrieta",
  "Jon Lester",
  "Kyle Hendricks",
  "Pedro Strop",
  "Carl Edwards Jr",
  "Albert Almora",
  "Ian Happ",
  "Nico Hoerner",
  "Cody Bellinger",
  "Dansby Swanson",
  "Marcus Stroman",
  "Seiya Suzuki",
  "Christopher Morel",
  "Justin Steele",
  "Jameson Taillon",
  "Matt Mervis",
  "Miguel Amaya",
  // More obscure Cubs 2008+
  "Kosuke Fukudome",
  "Ryan Theriot",
  "Reed Johnson",
  "Geovany Soto",
  "Aramis Ramirez",
  "Carlos Zambrano",
  "Ted Lilly",
  "Ryan Dempster",
  "Carlos Marmol",
  "Marlon Byrd",
  "Darwin Barney",
  "Starlin Castro",
  "Jeff Samardzija",
  "Travis Wood",
  "Chris Coghlan",
  "Tommy La Stella",
  "Hector Rondon",
  "Jorge Soler",
  "Tommy Hottovy",
  "Junior Lake",
  "David DeJesus",
  "Wellington Castillo",
  "Mike Olt",
  "Nate Schierholtz",
  "Luis Valbuena",
  "John Lackey",
  "Jason Heyward",
  "Wade Davis",
  "Brandon Morrow",
  "Steve Cishek",
  "Victor Caratini",
  "David Bote",
  "Mark Zagunis",
  "Taylor Davis",
  "Alec Mills",
  "Rowan Wick",
  "Jason Kipnis",
  "Cameron Maybin",
  "Jose Quintana",
  "Yu Darvish",
  "Craig Kimbrel",
  "Rafael Ortega",
  "Frank Schwindel",
  "Patrick Wisdom",
  "Yan Gomes",
  "Drew Smyly",
  "Adbert Alzolay",
  "Keegan Thompson",
  "Hayden Wesneski",
  "Michael Busch",
  "Pete Crow-Armstrong",
  "Brennen Davis",
  "Cade Horton",
];

/**
 * Generates a creative game name combining the current date with either
 * a Grateful Dead song or a Chicago athlete name.
 * Optionally excludes names that have been recently used.
 */
export function generateGameName(excludeNames: string[] = []): string {
  const dateStr = format(new Date(), "MMM d");
  const excludeSet = new Set(excludeNames);
  
  // Build list of all possible names
  const allPossibleNames = [
    ...GRATEFUL_DEAD_SONGS.map(song => `${dateStr} - ${song}`),
    ...PHISH_SONGS.map(song => `${dateStr} - ${song}`),
    ...PEORIA_STREETS.map(street => `${dateStr} - ${street}`),
    ...PEORIA_HIGH_SCHOOLS.map(school => `${dateStr} - ${school}`),
    ...PEORIA_CUSTOM.map(item => `${dateStr} - ${item}`),
    ...CHICAGO_ATHLETES.map(athlete => `${dateStr} - ${athlete}`)
  ];
  
  // Filter out excluded names
  const availableNames = allPossibleNames.filter(name => !excludeSet.has(name));
  
  // If all names are taken (unlikely), fall back to any random name
  if (availableNames.length === 0) {
    return allPossibleNames[Math.floor(Math.random() * allPossibleNames.length)];
  }
  
  return availableNames[Math.floor(Math.random() * availableNames.length)];
}
