project_id = "ehccrxumpibuoehfsmms"

[functions.enforce-deadlines]
verify_jwt = false

[functions.enforce-all-deadlines]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.generate-trivia]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.finalize-voice-operations]
verify_jwt = false

