DO $verify$ BEGIN
IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid='finalize_gameplay_transfer_batch()'::regprocedure AND md5(pg_get_functiondef(p.oid))='5d1c8703caee40ce7392d4eb6de1aaf9' AND pg_get_userbyid(p.proowner)='postgres' AND p.prosecdef=true AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=public']::text[] AND p.proacl::text='{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}') THEN RAISE EXCEPTION 'commit_boundary:metadata_or_immutable_owner_drift'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid='private.farkle_require_claim_v1(uuid,uuid,uuid)'::regprocedure AND md5(pg_get_functiondef(p.oid))='a1a357505f83fbe26d1c534bc8799886' AND pg_get_userbyid(p.proowner)='postgres' AND p.prosecdef=false AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=""']::text[] AND p.proacl::text='{postgres=X/postgres}') THEN RAISE EXCEPTION 'commit_boundary:metadata_or_immutable_owner_drift'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid='private.farkle_settle_v1(uuid)'::regprocedure AND md5(pg_get_functiondef(p.oid))='e4b72f5ee9376b4791e83be0db15ab9f' AND pg_get_userbyid(p.proowner)='postgres' AND p.prosecdef=true AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=""']::text[] AND p.proacl::text='{postgres=X/postgres}') THEN RAISE EXCEPTION 'commit_boundary:metadata_or_immutable_owner_drift'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid='farkle_apply_action(uuid,uuid,text,bigint,uuid,jsonb)'::regprocedure AND md5(pg_get_functiondef(p.oid))='44e9c9b5dbda2c5415fbdec19d2d3289' AND pg_get_userbyid(p.proowner)='postgres' AND p.prosecdef=true AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=""']::text[] AND p.proacl::text='{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}') THEN RAISE EXCEPTION 'commit_boundary:metadata_or_immutable_owner_drift'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='private.farkle_terminal_transfers_v2'::regclass AND relrowsecurity AND pg_get_userbyid(relowner)='postgres')
 OR has_table_privilege('authenticated','private.farkle_terminal_transfers_v2','INSERT')
 OR has_table_privilege('service_role','private.farkle_terminal_transfers_v2','INSERT')
 OR has_function_privilege('authenticated','private.farkle_begin_terminal_transfer_v2(uuid,bigint,jsonb,jsonb)','EXECUTE')
 OR has_function_privilege('service_role','private.farkle_begin_terminal_transfer_v2(uuid,bigint,jsonb,jsonb)','EXECUTE')
 THEN RAISE EXCEPTION 'commit_boundary:private_boundary'; END IF;
IF NOT EXISTS(SELECT 1 FROM private.farkle_release WHERE admin_only AND NOT creation_enabled AND NOT production_defaults_approved)
 OR EXISTS(SELECT 1 FROM public.game_defaults WHERE game_type='farkle')
 OR EXISTS(SELECT 1 FROM private.farkle_terminal_transfers_v2)
 THEN RAISE EXCEPTION 'commit_boundary:release_gate'; END IF;
END $verify$;
SELECT jsonb_build_object('commitBoundaryVerified',true,'release',(SELECT to_jsonb(x) FROM private.farkle_release x),'productionDefaults',0,'handoffs',0,'functions',(SELECT jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'securityDefiner',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text)) FROM pg_proc p WHERE p.oid IN ('private.farkle_settle_v1(uuid)'::regprocedure,'public.finalize_gameplay_transfer_batch()'::regprocedure,'private.farkle_begin_terminal_transfer_v2(uuid,bigint,jsonb,jsonb)'::regprocedure,'private.farkle_require_claim_v1(uuid,uuid,uuid)'::regprocedure,'public.farkle_apply_action(uuid,uuid,text,bigint,uuid,jsonb)'::regprocedure)));
